name: YanZhaoWang

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Execute Bash script
        run: |
          ls -al

          url="https://yz.chsi.com.cn/yzwb/"
          timeout=20
          target_string="准考证"


          content=$(curl --referer "https://www.baidu.com/s?wd=lnkszc" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" --connect-timeout $timeout -s "https://yz.chsi.com.cn/yzwb/" | grep -oP '<div class="yzwb-current-time">\K.*?(?=<)')

          if [ $? -eq 0 ]; then
            echo "$content"
            if [[ $content == *"$target_string"* ]]; then
              echo "已开放准考证打印"

              # 添加注释符号
              #sed -i 's/#push:/#&/' .github/workflows/YanZhaoWang.yml
              #sed -i 's/#schedule:/#&/' .github/workflows/YanZhaoWang.yml
              #sed -i '/cron:/,+1 s/^/#/' .github/workflows/YanZhaoWang.yml
              sed -i '5,7 s/^/#/' .github/workflows/YanZhaoWang.yml
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add -u .
              git commit -m "update by actions"
              git push
              echo "成功禁用当前workflow"

              exit 1
            else
              echo "未开放准考证打印"
              exit 0
            fi
          else
            echo "查询超时"
            exit 2
          fi
