name: Scheduled Workflow

on:
  workflow_dispatch:
  push:
  #schedule:
#    - cron: 10 16 * * *
#

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Execute Bash script
        run: |


          #!/bin/bash

          git config user.name github-actions
          git config user.email github-actions@github.com
          ls -al


          FILE=".github/workflows/YanZhaoWang.yml"  # 工作流程文件路径

          # 检查工作流程文件是否存在
          if [ ! -f "$FILE" ]; then
            echo "工作流程文件 $FILE 不存在"
            exit 1
          fi

          # 添加注释符号
          sed -i 's/##push:/#&/' .github/workflows/YanZhaoWang.yml
          sed -i 's/#schedule:/#&/' .github/workflows/YanZhaoWang.yml
#          sed -i '/cron:/,+1 s/^/#/' .github/workflows/YanZhaoWang.yml
#
          echo "成功在工作流程文件 $FILE 中添加注释符号"




          git add -u .
          git commit -m "update"
          git push

          content=$(curl -s "https://yz.chsi.com.cn/yzwb/" | grep -oP '<div class="yzwb-current-time">\K.*?(?=<)')

          # echo "$content"
          if [[ $content == *准考证* ]]; then
            echo "已开放准考证打印"
            exit 1
          else
            echo "未开放准考证打印"
            exit 0
          fi
