name: YanZhaoWang

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Execute Bash script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ls -al



          git add -u .
          git commit -m "update by actions"
          git push

          content=$(curl -s "https://yz.chsi.com.cn/yzwb/" | grep -oP '<div class="yzwb-current-time">\K.*?(?=<)')

          # echo "$content"
          if [[ $content == *确认* ]]; then
            echo "已开放准考证打印"
            
            # 添加注释符号
            #sed -i 's/#push:/#&/' .github/workflows/YanZhaoWang.yml
            #sed -i 's/#schedule:/#&/' .github/workflows/YanZhaoWang.yml
            #sed -i '/cron:/,+1 s/^/#/' .github/workflows/YanZhaoWang.yml
            sed -i '5,7 s/^/#/' .github/workflows/YanZhaoWang.yml
            echo "成功禁用当前workflow"

            exit 1
          else
            echo "未开放准考证打印"
            exit 0
          fi
