name: Scheduled Workflow

on:
  workflow_dispatch:
  push:


jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Bash script
        run: |
          
          #!/bin/bash

          content=$(curl -s "https://yz.chsi.com.cn/yzwb/" | grep -oP '<div class="yzwb-current-time">\K.*?(?=<)')

          # echo "$content"
          if [[ $content == *准考证* ]]; then
            echo "已开放准考证打印"
            echo "Found a link with text 'A'. Disabling workflow..."
            echo "::set-env name=DISABLE_WORKFLOW::true"
          else
            echo "未开放准考证打印"
            exit 0  # 如果文本内容不为"A"，则以退出码1退出
          fi
         

      - name: Disable Workflow
        if: env.DISABLE_WORKFLOW == 'true'
        run: echo "This workflow has been disabled." && exit 1
